# SPDX-FileCopyrightText: 2021 GSMA and all contributors.
#
# SPDX-License-Identifier: Apache-2.0

# options for analysis running
linters-settings:
  errcheck:
    check-type-assertions: true
  goconst:
    min-len: 2
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  govet:
    check-shadowing: true
  nolintlint:
    require-explanation: true
    require-specific: true

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
#    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - exhaustive
    - goconst
#    - gocritic
    - gofmt
#    - goimports
    - gomnd
    - gocyclo
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - nakedret
    - prealloc
    - predeclared
    - staticcheck
    - structcheck
    - stylecheck
#    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - varcheck
    - whitespace
#    - wsl

run:
  issues-exit-code: 1
  # include test files or not, default is true
  tests: true

  skip-dirs:
    - test/mocks
    - test/stubs
    - test/historyshimtest

issues:
  exclude-rules:
    - linters:
        - staticcheck
      text: "SA1019: package hybrid/test/historyshimtest is deprecated"
    - linters:
        - staticcheck
      text: "SA1019: package github.com/golang/protobuf/proto is deprecated"
