name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
      - ssch
  pull_request:
jobs:
  go-mod:
    name: verify go mod changes
    runs-on: ubuntu-latest
    steps:
      - name: install go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: checkout source
        uses: actions/checkout@v2
      - name: check go mod
        run: |
          cd hybrid
          go mod tidy
          git diff --exit-code go.mod
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.33

          # Optional: working directory, useful for monorepos
          working-directory: hybrid

          # Optional: golangci-lint command line arguments.
          # args: --issues-exit-code=0

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          # only-new-issues: true
