# SPDX-FileCopyrightText: 2021 the BWRP-chaincode contributors.
#
# SPDX-License-Identifier: Apache-2.0
name: go-reuse
on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
      - ssch*
  pull_request:
jobs:
  license-check:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - name: REUSE Compliance Check
      uses: fsfe/reuse-action@v1
  