# SPDX-FileCopyrightText: 2021 the BWRP-chaincode contributors.
#
# SPDX-License-Identifier: Apache-2.0
name: go-test
on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
      - ssch*
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: install go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    - name: checkout source
      uses: actions/checkout@v2
    - name: generate certs
      run: | 
        cd hybrid
        test/scripts/gencert_all.sh > test/data/organizations.go
    - name: run test
      run: |
        cd hybrid
        ./test.sh
